import type {
  NavigationResponse,
  HeroResponse,
  FooterResponse,
  Service,
  Testimonial,
  Client,
} from "@/types";

export const fallbackData = {
  navigation: {
    navItems: [
      {
        id: "1",
        name: "What we offer",
        key: "what-we-offer",
        href: null,
        position: 1,
        isActive: true,
        hasDropdown: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        name: "Who we serve",
        key: "who-we-serve",
        href: null,
        position: 2,
        isActive: true,
        hasDropdown: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "3",
        name: "Why Paywell",
        key: "why-paywell",
        href: null,
        position: 3,
        isActive: true,
        hasDropdown: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "4",
        name: "Careers",
        key: "careers",
        href: "/careers",
        position: 4,
        isActive: true,
        hasDropdown: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "5",
        name: "About",
        key: "about",
        href: "/about",
        position: 5,
        isActive: true,
        hasDropdown: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "6",
        name: "Paywell",
        key: "paywell",
        href: "/paywell",
        position: 6,
        isActive: true,
        hasDropdown: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    dropdownData: {
      "what-we-offer": {
        title: "What We Offer",
        items: [
          {
            id: "1",
            dropdownDataId: "1",
            name: "Payroll Management",
            href: "/services/payroll",
            description:
              "Streamline your payroll process with our comprehensive PayWell Plus system. Handle salaries, deductions, taxes, and compliance automatically.",
            features: [
              "Automated Calculations",
              "KRA Tax Compliance",
              "NSSF & NHIF Integration",
              "Employee Self-Service Portal",
            ],
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "2",
            dropdownDataId: "1",
            name: "Recruitment Services",
            href: "/services/recruitment",
            description:
              "Professional recruitment and headhunting services for local and international companies. Attract and retain top talent.",
            features: [
              "Executive Search",
              "Bulk Recruitment",
              "Skills Assessment",
              "Background Verification",
            ],
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "3",
            dropdownDataId: "1",
            name: "AI Solutions",
            href: "/services/ai-solutions",
            description:
              "Cutting-edge AI solutions to enhance your business processes and drive innovation.",
            features: [
              "Machine Learning",
              "Natural Language Processing",
              "Computer Vision",
              "Robotic Process Automation",
            ],
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "4",
            dropdownDataId: "1",
            name: "Staff Outsourcing",
            href: "/services/outsourcing",
            description:
              "Complete staff outsourcing solutions allowing you to focus on core business while we handle HR operations.",
            features: [
              "Full HR Management",
              "Payroll Processing",
              "Compliance Handling",
              "Employee Benefits",
            ],
            position: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "5",
            dropdownDataId: "1",
            name: "HR Consulting",
            href: "/services/hr-consulting",
            description:
              "Expert HR consulting services to optimize your human resource strategies and improve organizational performance.",
            features: [
              "Policy Development",
              "Process Optimization",
              "Training Programs",
              "Performance Management",
            ],
            position: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "6",
            dropdownDataId: "1",
            name: "Time & Attendance",
            href: "/services/attendance",
            description:
              "Smart time tracking with automated scheduling and biometric integration for accurate attendance management.",
            features: [
              "Biometric Integration",
              "Mobile Clock-in",
              "Shift Management",
              "Overtime Tracking",
            ],
            position: 6,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "7",
            dropdownDataId: "1",
            name: "HR System",
            href: "/technology/hr-system",
            description:
              "Complete HR management system for employee records, leave management, and performance tracking.",
            features: [
              "Employee Database",
              "Leave Management",
              "Performance Reviews",
              "Document Management",
            ],
            position: 7,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "8",
            dropdownDataId: "1",
            name: "CCTV Solutions",
            href: "/security/cctv",
            description:
              "Professional CCTV installation and monitoring solutions for enhanced security and workplace safety.",
            features: [
              "HD Camera Installation",
              "24/7 Monitoring",
              "Cloud Storage",
              "Remote Access",
            ],
            position: 8,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "9",
            dropdownDataId: "1",
            name: "Software Development",
            href: "/technology/software-development",
            description:
              "Custom web development services to build powerful, scalable websites and web applications for your business.",
            features: [
              "Custom Websites",
              "E-commerce Solutions",
              "Mobile Responsive",
              "SEO Optimized",
            ],
            position: 9,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      "who-we-serve": {
        title: "Who We Serve",
        items: [
          {
            id: "10",
            dropdownDataId: "2",
            name: "Small Business (1-50)",
            href: "/clients/small-business",
            description:
              "Perfect for growing companies with 1-50 employees. Enterprise-level HR capabilities at affordable prices.",
            features: [
              "Basic Payroll",
              "Employee Records",
              "Time Tracking",
              "Leave Management",
            ],
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "11",
            dropdownDataId: "2",
            name: "Medium Enterprise (51-500)",
            href: "/clients/medium-business",
            description:
              "Scalable HR solutions for medium enterprises with 51-500 employees. Advanced features for growing teams.",
            features: [
              "Advanced Payroll",
              "Performance Management",
              "Recruitment Tools",
              "Analytics Dashboard",
            ],
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "12",
            dropdownDataId: "2",
            name: "Large Enterprise (500+)",
            href: "/clients/enterprise",
            description:
              "Enterprise-grade HR solutions for large organizations with 500+ employees. Complete customization and dedicated support.",
            features: [
              "Custom Workflows",
              "Advanced Analytics",
              "Multi-location Support",
              "Dedicated Account Manager",
            ],
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      "why-paywell": {
        title: "Why Paywell",
        items: [
          {
            id: "13",
            dropdownDataId: "3",
            name: "Local Expertise",
            href: "/why-paywell/local-expertise",
            description:
              "15+ years of experience in the Kenyan market with deep understanding of local business challenges and regulations.",
            features: [
              "KRA Integration",
              "NSSF Compliance",
              "NHIF Processing",
              "Local Banking Support",
            ],
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "14",
            dropdownDataId: "3",
            name: "24/7 Support",
            href: "/why-paywell/support",
            description:
              "Round-the-clock support from our expert team to ensure your HR operations never stop.",
            features: [
              "Phone Support",
              "Live Chat",
              "Email Support",
              "On-site Assistance",
            ],
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "15",
            dropdownDataId: "3",
            name: "Security & Compliance",
            href: "/why-paywell/security",
            description:
              "Bank-level security with full compliance to Kenyan data protection laws and international standards.",
            features: [
              "ISO 27001 Certified",
              "Data Encryption",
              "Regular Audits",
              "GDPR Compliant",
            ],
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
    },
    themeConfig: {
      id: "default",
      primaryColor: "#3b82f6",
      accentColor: "#f97316",
      logoUrl: "/logo.png",
      companyName: "Fortune Technologies",
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  } as NavigationResponse,

  hero: {
    heroDashboards: [
      {
        id: "1",
        title: "HR Dashboard",
        description:
          "Complete overview of your HR operations with real-time insights",
        type: "content",
        stats: [
          {
            color: "primary",
            label: "Active Employees",
            value: "2,847",
          },
          {
            color: "accent",
            label: "Payroll Accuracy",
            value: "98.2%",
          },
        ],
        features: [
          "Payroll Processing",
          "Time Tracking",
          "Benefits Management",
        ],
        position: 1,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        title: "Analytics Center",
        description: "Data-driven insights into workforce performance",
        type: "content",
        stats: [
          {
            color: "primary",
            label: "Reports Generated",
            value: "1,234",
          },
          {
            color: "accent",
            label: "Data Accuracy",
            value: "99.8%",
          },
        ],
        features: ["Real-time Analytics", "Custom Reports", "Trend Analysis"],
        position: 2,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    heroContent: {
      id: "default",
      trustBadge: "Trusted by 5,000+ Companies",
      mainHeading: "Transform Your",
      subHeading: "HR Operations",
      tagline: "with AI-Powered Solutions",
      description:
        "Streamline payroll, optimize talent management, and enhance employee experiences with Fortune Technologies' comprehensive HR platform designed for modern businesses.",
      trustPoints: ["No Setup Fees", "24/7 Support", "GDPR Compliant"],
      primaryCtaText: "Get a Quote",
      secondaryCtaText: "Contact Us",
      primaryCtaLink: "/contact",
      secondaryCtaLink: "/contact",
      phoneNumber: "0733769149",
      chatWidgetUrl: "https://rag-chat-widget.vercel.app/",
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  } as HeroResponse,

  footer: {
    sections: [
      {
        id: "1",
        title: "HR Solutions",
        position: 1,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        links: [
          {
            id: "1",
            footerSectionId: "1",
            name: "Payroll Management",
            href: "/services/payroll",
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "2",
            footerSectionId: "1",
            name: "Time & Attendance",
            href: "/services/attendance",
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "3",
            footerSectionId: "1",
            name: "HR Consulting",
            href: "/services/hr-consulting",
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "4",
            footerSectionId: "1",
            name: "Staff Outsourcing",
            href: "/services/outsourcing",
            position: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "5",
            footerSectionId: "1",
            name: "HR System",
            href: "/technology/hr-system",
            position: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "2",
        title: "Technology",
        position: 2,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        links: [
          {
            id: "6",
            footerSectionId: "2",
            name: "Software Development",
            href: "/technology/software-development",
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "7",
            footerSectionId: "2",
            name: "CCTV Solutions",
            href: "/security/cctv",
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "8",
            footerSectionId: "2",
            name: "Mobile App",
            href: "/services/mobile-app",
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "9",
            footerSectionId: "2",
            name: "Data Security",
            href: "/services/data-security",
            position: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "10",
            footerSectionId: "2",
            name: "AI Solutions",
            href: "/services/ai-solutions",
            position: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "3",
        title: "Support",
        position: 3,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        links: [
          {
            id: "11",
            footerSectionId: "3",
            name: "Help Center",
            href: "/support",
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "12",
            footerSectionId: "3",
            name: "Documentation",
            href: "/docs",
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "13",
            footerSectionId: "3",
            name: "About Us",
            href: "/about",
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "14",
            footerSectionId: "3",
            name: "Careers",
            href: "/careers",
            position: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "15",
            footerSectionId: "3",
            name: "Contact Us",
            href: "/contact",
            position: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "4",
        title: "Industries",
        position: 4,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        links: [
          {
            id: "16",
            footerSectionId: "4",
            name: "Small Business",
            href: "/clients/small-business",
            position: 1,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "17",
            footerSectionId: "4",
            name: "Healthcare",
            href: "/industries/healthcare",
            position: 2,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "18",
            footerSectionId: "4",
            name: "Manufacturing",
            href: "/industries/manufacturing",
            position: 3,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "19",
            footerSectionId: "4",
            name: "Retail & Commerce",
            href: "/industries/retail",
            position: 4,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
          {
            id: "20",
            footerSectionId: "4",
            name: "Financial Services",
            href: "/industries/finance",
            position: 5,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          },
        ],
      },
    ],
    contactInfo: [
      {
        id: "1",
        type: "phone",
        label: "Phone",
        value: "+254 722 769 149",
        icon: "Phone",
        isActive: true,
        position: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        type: "email",
        label: "Email",
        value: "support@fortunekenya.com",
        icon: "Mail",
        isActive: true,
        position: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "3",
        type: "address",
        label: "Address",
        value: "SouthGate Centre, Nairobi, Kenya",
        icon: "MapPin",
        isActive: true,
        position: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    socialLinks: [
      {
        id: "1",
        name: "LinkedIn",
        icon: "Linkedin",
        href: "https://linkedin.com/company/fortune-technologies",
        isActive: true,
        position: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        name: "Twitter",
        icon: "Twitter",
        href: "https://twitter.com/@fcl_kenya",
        isActive: true,
        position: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "3",
        name: "Facebook",
        icon: "Facebook",
        href: "https://facebook.com/fortunetechnologies",
        isActive: true,
        position: 3,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "4",
        name: "YouTube",
        icon: "Youtube",
        href: "https://youtube.com/@fortunetechnologies",
        isActive: true,
        position: 4,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  } as FooterResponse,

  services: [
    {
      id: "1",
      title: "Payroll Management",
      slug: "payroll",
      category: "HR Solutions",
      description:
        "Comprehensive payroll processing with automated calculations, tax compliance, and statutory deductions.",
      shortDesc:
        "Automate your payroll processing with our intelligent system.",
      icon: "DollarSign",
      color:
        "bg-primary-100 text-primary-600 dark:bg-primary-900/20 dark:text-primary-400",
      features: [
        "Automated salary calculations",
        "Tax compliance & reporting",
        "Multi-currency support",
        "Employee self-service portal",
      ],
      onQuote: true,
      hasProcess: true,
      hasCompliance: true,
      isActive: true,
      isFeatured: true,
      isPopular: true,
      position: 1,
      buttonText: "Learn More",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      title: "Recruitment Services",
      slug: "recruitment",
      category: "HR Solutions",
      description:
        "End-to-end recruitment solutions with AI-powered candidate screening and onboarding.",
      shortDesc: "Find and hire the best talent with our recruitment platform.",
      icon: "Users",
      color:
        "bg-orange-100 text-orange-600 dark:bg-orange-900/20 dark:text-orange-400",
      features: [
        "AI-powered candidate matching",
        "Automated screening",
        "Interview scheduling",
        "Digital onboarding",
      ],
      onQuote: true,
      hasProcess: true,
      hasCompliance: false,
      isActive: true,
      isFeatured: true,
      isPopular: false,
      position: 2,
      buttonText: "Get Started",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      title: "Time & Attendance",
      slug: "attendance",
      category: "HR Solutions",
      description:
        "Smart attendance tracking with biometric integration and real-time reporting.",
      shortDesc: "Track employee attendance with biometric precision.",
      icon: "Clock",
      color:
        "bg-green-100 text-green-600 dark:bg-green-900/20 dark:text-green-400",
      features: [
        "Biometric integration",
        "Real-time tracking",
        "Leave management",
        "Shift scheduling",
      ],
      onQuote: true,
      hasProcess: false,
      hasCompliance: true,
      isActive: true,
      isFeatured: false,
      isPopular: true,
      position: 3,
      buttonText: "View Details",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      title: "HR Management System",
      slug: "hr-system",
      category: "Technology",
      description:
        "All-in-one cloud-based HRMS for complete employee lifecycle management.",
      shortDesc: "Comprehensive HR solution for modern businesses.",
      icon: "Database",
      color:
        "bg-purple-100 text-purple-600 dark:bg-purple-900/20 dark:text-purple-400",
      features: [
        "Employee database",
        "Performance management",
        "Training & development",
        "Analytics & reporting",
      ],
      onQuote: true,
      hasProcess: true,
      hasCompliance: true,
      isActive: true,
      isFeatured: true,
      isPopular: true,
      position: 4,
      buttonText: "Explore Features",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "5",
      title: "Staff Outsourcing",
      slug: "outsourcing",
      category: "HR Solutions",
      description:
        "Professional staff outsourcing services for temporary and permanent placements.",
      shortDesc: "Access skilled professionals for your projects.",
      icon: "Briefcase",
      color: "bg-pink-100 text-pink-600 dark:bg-pink-900/20 dark:text-pink-400",
      features: [
        "Skilled workforce pool",
        "Flexible contracts",
        "Compliance management",
        "Quick deployment",
      ],
      onQuote: true,
      hasProcess: true,
      hasCompliance: true,
      isActive: true,
      isFeatured: false,
      isPopular: false,
      position: 5,
      buttonText: "Request Staff",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "6",
      title: "CCTV Solutions",
      slug: "cctv-solutions",
      category: "Security",
      description:
        "Advanced CCTV surveillance systems with cloud storage and AI analytics.",
      shortDesc: "Secure your premises with intelligent surveillance.",
      icon: "Camera",
      color:
        "bg-indigo-100 text-indigo-600 dark:bg-indigo-900/20 dark:text-indigo-400",
      features: [
        "HD cameras",
        "Cloud storage",
        "AI-powered alerts",
        "24/7 monitoring",
      ],
      onQuote: true,
      hasProcess: false,
      hasCompliance: false,
      isActive: true,
      isFeatured: false,
      isPopular: false,
      position: 6,
      buttonText: "Get Quote",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ] as unknown as Service[],

  fallbackAboutData: {
    hero: {
      title: "Transforming Businesses",
      subtitle: "Through People",
      description:
        "For over 20 years, Fortune Technologies has been Kenya's leading HR solutions provider, empowering businesses to focus on growth while we handle their human resource operations with cutting-edge technology and expert service.\n\nWith 5,000+ clients and managing over 1 million employees across East Africa, we have proven expertise in delivering scalable HR solutions that drive business success.",
      heroImage: "",
      heroImageAlt: "Fortune Technologies Team",
    },
    mission: {
      title: "Our Mission",
      content:
        "To be THE CHOICE of Client as Strategic Partner in Human Resource and ICT",
      icon: "Target",
    },
    vision: {
      title: "Our Vision",
      content:
        "Fortune strives to seamlessly get integrated into Customers' business as an inevitable HR and ICT services provider.",
      icon: "Globe",
    },
    history: {
      title: "Our Journey Through the Years",
      description:
        "From a small consulting firm to East Africa's leading HR technology provider.",
      timeline: [
        {
          year: "2002",
          title: "Company Founded",
          description:
            "Started as a small HR consulting firm in Nairobi with a vision to transform HR operations.",
        },
        {
          year: "2010",
          title: "First Software Launch",
          description:
            "Launched our first payroll management software, serving 50 companies in the first year.",
        },
        {
          year: "2015",
          title: "Regional Expansion",
          description:
            "Expanded operations to Uganda and Tanzania, serving 500+ companies across East Africa.",
        },
        {
          year: "2020",
          title: "1000+ Clients Milestone",
          description:
            "Reached 1000+ active clients, managing over 500,000 employees across the region.",
        },
        {
          year: "2024",
          title: "5000+ Clients",
          description:
            "Now serving 5000+ companies with comprehensive HR solutions and managing 1M+ employees.",
        },
      ],
    },
    team: {
      title: "Meet Our Leadership Team",
      description:
        "Experienced leaders driving innovation and excellence in HR technology across East Africa.",
      members: [
        {
          name: "Vincent Abwao",
          role: "Lead Consultant ",
          bio: "15+ years in HR technology and business leadership. Previously led digital transformation at major Kenyan corporations.",
          image: "",
          linkedin: "https://linkedin.com/in/",
          specialties: [
            "Strategic Leadership",
            "Digital Transformation",
            "Business Development",
          ],
        },
      ],
    },
    values: [
      {
        title: "Integrity",
        description:
          "We conduct business with the highest ethical standards and transparency.",
        icon: "Shield",
        color:
          "bg-primary-100 text-primary-600 dark:bg-primary-900/20 dark:text-primary-400",
      },
      {
        title: "Client-Centric",
        description:
          "Our clients success is our success. We put your needs at the center of everything we do.",
        icon: "Users",
        color:
          "bg-green-100 text-green-600 dark:bg-green-900/20 dark:text-green-400",
      },
      {
        title: "Innovation",
        description:
          "We continuously innovate to provide cutting-edge HR solutions and technology.",
        icon: "Zap",
        color:
          "bg-purple-100 text-purple-600 dark:bg-purple-900/20 dark:text-purple-400",
      },
      {
        title: "Excellence",
        description:
          "We strive for excellence in every service we deliver and relationship we build.",
        icon: "Award",
        color:
          "bg-orange-100 text-orange-600 dark:bg-orange-900/20 dark:text-orange-400",
      },
    ],
    seo: {
      metaTitle:
        "About Fortune Technologies - Leading HR Solutions in East Africa",
      metaDescription:
        "Learn about Fortune Technologies, Kenya's premier HR solutions provider with 20+ years of experience, serving 5000+ clients across East Africa.",
      keywords: [
        "Fortune Technologies",
        "HR Solutions Kenya",
        "About Us",
        "Company History",
        "Leadership Team",
      ],
    },
  },

  testimonials: [
    {
      id: "1",
      name: "Sarah Wanjiku",
      role: "HR Director",
      company: "Safaricom PLC",
      content: "Fortune Technologies completely transformed our HR operations. The payroll automation saved us 20 hours per week, and employee satisfaction increased by 45%.",
      rating: 5,
      avatar: "https://images.unsplash.com/photo-1494790108755-2616b612c37c?w=150&h=150&fit=crop&crop=face",
      results: [
        "20hrs saved weekly",
        "45% satisfaction boost",
        "100% compliance",
      ],
      service: "payroll",
      category: null,
      isActive: true,
      isFeatured: true,
      position: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      name: "Michael Kiprotich",
      role: "CEO",
      company: "TechNova Kenya",
      content: "The AI-powered recruitment features helped us reduce hiring time by 60%. The integration with KRA and NSSF is seamless.",
      rating: 5,
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
      results: [
        "60% faster hiring",
        "Seamless KRA integration",
        "ROI in 2 months",
      ],
      service: "recruitment",
      category: null,
      isActive: true,
      isFeatured: true,
      position: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      name: "Grace Muthoni",
      role: "Operations Manager",
      company: "Equity Bank",
      content: "The time and attendance system has eliminated buddy punching completely. Our payroll accuracy improved to 99.9%.",
      rating: 5,
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
      results: [
        "Zero buddy punching",
        "99.9% payroll accuracy",
        "Real-time tracking",
      ],
      service: "attendance",
      category: null,
      isActive: true,
      isFeatured: false,
      position: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ] as unknown as Testimonial[],

  faqCategories: [
    {
      id: "1",
      name: "Account & Profile",
      key: "account",
      icon: "User",
      description: "Questions about account management and profile settings",
      faqCount: 3,
      position: 0,
      isActive: true,
    },
    {
      id: "2",
      name: "Services",
      key: "services",
      icon: "Briefcase",
      description: "Information about our HR and business services",
      faqCount: 4,
      position: 1,
      isActive: true,
    },
    {
      id: "3",
      name: "Billing & Payments",
      key: "billing",
      icon: "CreditCard",
      description: "Payment methods, invoicing, and billing questions",
      faqCount: 2,
      position: 2,
      isActive: true,
    },
    {
      id: "4",
      name: "Privacy & Security",
      key: "privacy",
      icon: "Shield",
      description: "Data protection, security, and privacy policies",
      faqCount: 2,
      position: 3,
      isActive: true,
    },
    {
      id: "5",
      name: "Support",
      key: "support",
      icon: "MessageSquare",
      description: "Customer support and assistance",
      faqCount: 2,
      position: 4,
      isActive: true,
    },
  ],

  faqs: [
    {
      id: "1",
      question: "How do I create an account?",
      answer:
        "You can create an account by clicking the 'Sign Up' button on the careers page. You'll need to provide your email address, create a password, and verify your email. You can also sign up using your LinkedIn or Google account for faster registration.",
      category: {
        id: "1",
        name: "Account & Profile",
        key: "account",
        icon: "User",
      },
      isPopular: true,
      tags: ["account", "registration", "sign-up"],
      views: 150,
      helpfulCount: 45,
      position: 0,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      question: "How can I update my profile information?",
      answer:
        "Log into your account and go to 'Profile Settings'. Here you can update your personal information, work experience, skills, and upload a new resume. Changes are saved automatically, and you can preview how your profile appears to employers.",
      category: {
        id: "1",
        name: "Account & Profile",
        key: "account",
        icon: "User",
      },
      isPopular: false,
      tags: ["profile", "update", "settings"],
      views: 89,
      helpfulCount: 32,
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      question: "Can I reset my password?",
      answer:
        "Yes, click 'Forgot Password' on the login page. Enter your email address and we'll send you a secure link to reset your password. The link expires after 24 hours for security reasons.",
      category: {
        id: "1",
        name: "Account & Profile",
        key: "account",
        icon: "User",
      },
      isPopular: false,
      tags: ["password", "reset", "security"],
      views: 67,
      helpfulCount: 28,
      position: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      question: "What HR services do you offer?",
      answer:
        "We offer comprehensive HR solutions including payroll management, recruitment services, HR consulting, employee benefits administration, compliance management, and performance management systems. Each service is tailored to meet your specific business needs.",
      category: {
        id: "2",
        name: "Services",
        key: "services",
        icon: "Briefcase",
      },
      isPopular: true,
      tags: ["services", "hr", "payroll", "recruitment"],
      views: 203,
      helpfulCount: 78,
      position: 0,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "5",
      question: "How do I apply for a job?",
      answer:
        "Browse our careers page, find a position that matches your skills, and click 'Apply Now'. You'll need to create an account, upload your resume, and complete the application form. You can track your application status in your dashboard.",
      category: {
        id: "2",
        name: "Services",
        key: "services",
        icon: "Briefcase",
      },
      isPopular: true,
      tags: ["jobs", "careers", "application"],
      views: 178,
      helpfulCount: 65,
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "6",
      question: "Do you offer payroll services for small businesses?",
      answer:
        "Yes, we provide scalable payroll solutions for businesses of all sizes. Our payroll services include salary processing, tax calculations, statutory deductions, payslip generation, and compliance reporting.",
      category: {
        id: "2",
        name: "Services",
        key: "services",
        icon: "Briefcase",
      },
      isPopular: false,
      tags: ["payroll", "small-business", "services"],
      views: 112,
      helpfulCount: 43,
      position: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "7",
      question: "What is your recruitment process?",
      answer:
        "Our recruitment process includes job analysis, candidate sourcing, screening, interviews, background checks, and onboarding support. We work closely with clients to understand their needs and find the best talent match.",
      category: {
        id: "2",
        name: "Services",
        key: "services",
        icon: "Briefcase",
      },
      isPopular: false,
      tags: ["recruitment", "hiring", "process"],
      views: 95,
      helpfulCount: 38,
      position: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "8",
      question: "What payment methods do you accept?",
      answer:
        "We accept major credit cards (Visa, Mastercard), mobile money (M-Pesa, Airtel Money), and bank transfers. All payments are processed securely through our encrypted payment system with PCI DSS compliance.",
      category: {
        id: "3",
        name: "Billing & Payments",
        key: "billing",
        icon: "CreditCard",
      },
      isPopular: true,
      tags: ["payment", "billing", "mpesa", "methods"],
      views: 134,
      helpfulCount: 56,
      position: 0,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "9",
      question: "How do I get an invoice for my payment?",
      answer:
        "Invoices are automatically generated and sent to your registered email after each payment. You can also download invoices from your account dashboard under 'Billing History'. Invoices include full transaction details and payment receipts.",
      category: {
        id: "3",
        name: "Billing & Payments",
        key: "billing",
        icon: "CreditCard",
      },
      isPopular: false,
      tags: ["invoice", "receipt", "billing"],
      views: 78,
      helpfulCount: 32,
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "10",
      question: "Is my personal information safe?",
      answer:
        "Yes, we take data security very seriously. We use industry-standard encryption (256-bit SSL), secure servers, and comply with GDPR and local data protection regulations. Your information is never sold to third parties, and you have full control over your privacy settings.",
      category: {
        id: "4",
        name: "Privacy & Security",
        key: "privacy",
        icon: "Shield",
      },
      isPopular: true,
      tags: ["security", "privacy", "data-protection", "gdpr"],
      views: 167,
      helpfulCount: 89,
      position: 0,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "11",
      question: "How is my data used?",
      answer:
        "Your data is used solely to provide our services, improve user experience, and communicate important updates. We follow strict privacy policies and never share your data without consent. You can request data deletion or export at any time.",
      category: {
        id: "4",
        name: "Privacy & Security",
        key: "privacy",
        icon: "Shield",
      },
      isPopular: false,
      tags: ["privacy", "data-usage", "policy"],
      views: 92,
      helpfulCount: 41,
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "12",
      question: "How can I contact customer support?",
      answer:
        "You can reach us through multiple channels: email (support@fortunekenya.com), phone (+254 722 769 149), live chat on our website, or through the contact form. Our support team is available Monday-Friday, 8 AM-6 PM EAT, with emergency support available 24/7.",
      category: {
        id: "5",
        name: "Support",
        key: "support",
        icon: "MessageSquare",
      },
      isPopular: true,
      tags: ["support", "contact", "help", "customer-service"],
      views: 145,
      helpfulCount: 67,
      position: 0,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "13",
      question: "What are your support hours?",
      answer:
        "Our support team is available Monday to Friday, 8:00 AM to 6:00 PM (East Africa Time). We offer 24/7 emergency support for critical issues. Average response time is 4 hours during business hours and 24 hours for non-urgent queries.",
      category: {
        id: "5",
        name: "Support",
        key: "support",
        icon: "MessageSquare",
      },
      isPopular: false,
      tags: ["support", "hours", "availability"],
      views: 86,
      helpfulCount: 34,
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  clients: [
    {
      id: "1",
      name: "Kenya Association of Investment Groups",
      logo: "/clients/kaig.png",
      industry: "Technology",
      website: "https://kaig.org/",
      position: 1,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      name: "Chancery",
      logo: "/clients/chancery.jpg",
      industry: "Insurance",
      website: "https://chancerywright.com/",
      position: 2,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      name: "KWAL",
      logo: "/clients/kwal.png",
      industry: "Manufacturing",
      website: "https://www.kwal.co.ke/",
      position: 3,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      name: "Consolata",
      logo: "/clients/consolata-school.png",
      industry: "Missionary",
      website: "https://consolatashrine.org/consolata-missionaries/",
      position: 4,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "5",
      name: "Takaful",
      logo: "/clients/takaful.png",
      industry: "Insurance",
      website: "https://takaful.co.ke/",
      position: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "6",
      name: "Tetra Pak",
      logo: "/clients/tetra.png",
      industry: "Packaging",
      website: "https://www.tetrapak.com/",
      position: 6,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "7",
      name: "Magnate",
      logo: "/clients/magnate.png",
      industry: "Advertising",
      website: "https://magnate-ventures.com/",
      position: 7,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "8",
      name: "Longhorn",
      logo: "/clients/longhorn.jpg",
      industry: "Publishing",
      website: "https://longhornpublishers.com/",
      position: 8,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "9",
      name: "GenAfrica",
      logo: "/clients/genafrica.png",
      industry: "Asset Management",
      website: "https://genafrica.com/",
      position: 9,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ] as Client[],

   stats: [
    {
      id: "1",
      number: "5,000+",
      label: "Companies Trust Us",
      icon: "Users",
      color: "text-primary-600",
      isActive: true,
      position: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "2",
      number: "1M+",
      label: "Employees Managed",
      icon: "TrendingUp",
      color: "text-orange-600",
      isActive: true,
      position: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "3",
      number: "99.9%",
      label: "Uptime Guarantee",
      icon: "Shield",
      color: "text-green-600",
      isActive: true,
      position: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "4",
      number: "24/7",
      label: "Customer Support",
      icon: "Clock",
      color: "text-purple-600",
      isActive: true,
      position: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],


};